language: ruby

# whitelist
branches:  
  only:
    - master

services:  
    - docker

before_install:  
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker pull microsoft/aspnetcore-build:2
    - docker pull microsoft/aspnetcore:2

script:  
    - docker build --no-cache -t shamus03/xmlcombiner .
    - docker tag shamus03/xmlcombiner:latest shamus03/xmlcombiner:$TRAVIS_BUILD_NUMBER
    - docker push shamus03/xmlcombiner
