version: '2'
services:
  web:
    image: shamus03/xmlcombiner
    build: .
    ports:
      - "8001:80"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: xmlcombiner
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword